import type { Metadata } from "next";
import "./globals.css";
import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import Root from "./root";
import { Jost } from 'next/font/google';

const inter = Jost({ subsets: ["latin"], weight:['400','200','300','600','700','900'] });

export const metadata: Metadata = {
  title: "Akya Butik",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}:{
  children: React.ReactNode;
}) {
  return (
    <html lang="tr">
      <body suppressHydrationWarning={true} className={`${inter.className} antialiased`}>
        <Root> {children} </Root>
      </body>
    </html>
  );
}
